### ISSUE TITLE
Time cost of traditional Method

### ISSUE THREAD

**Issue by Yuliang-Huang** [Ruyi-Zha/r2_gaussian#28]
Dear authors,

Thanks a lot for your great work. I have aquestion on the time cost of traditional methods in table 1 of your paper.

I have tried running the "run_traditional_methods.py" script on the synthetic dataset "0_chest_coe.pickle" with 50 views, and it doesn't take a long time for SART. Below is the output:

Run sart... [15/01 11:27:54]
SART algorithm in progress. [15/01 11:27:55]
Estimated time until completion : 00:00:47 [15/01 11:27:57]
[sart] psnr_3d: 30.403564453125, ssim_3d: 0.7315470973650614 [15/01 11:28:52t

That's actually consistent with my impression on the speed of iterative reconsrtuction algorithm (It just takes 2~8 ms for one update of an image of size 256^3 with one projection of size 512^2)

Could you please give me some clues how you get the time in table 1? Many thanks!

Best,
Yuliang

**Comment by Ruyi-Zha** [comment]
Hi, we ensured that all experiments were conducted on the same machine. For the experiments, we used TIGRE v2.3 to run FDK, SART, and ASD-POCS, and the results are attached below. However, after submitting the paper, I noticed that using TIGRE v3.0 could improve speed, likely due to engineering optimizations in the newer version.

That said, given the significant quality gap between traditional methods and ours, I believe this difference does not impact the conclusions drawn in the paper. I hope this addresses your concerns.

0_chest_cone: 50 view
```
fdk:
  method: fdk
  psnr_3d: 24.367687225341797
  ssim_3d: 0.38344605763753253
  ssim_3d_x: 0.38980358839035034
  ssim_3d_y: 0.38659173250198364
  ssim_3d_z: 0.37394285202026367
  duration (sec): 0.2753901481628418
  duration (min): 0.00458983580271403
sart:
  method: sart
  psnr_3d: 31.857433319091797
  ssim_3d: 0.7921701073646545
  ssim_3d_x: 0.7816925048828125
  ssim_3d_y: 0.7953984141349792
  ssim_3d_z: 0.7994194030761719
  duration (sec): 216.78598427772522
  duration (min): 3.613099737962087
asd_pocs:
  method: asd_pocs
  psnr_3d: 32.36898422241211
  ssim_3d: 0.8807981212933859
  ssim_3d_x: 0.8791179656982422
  ssim_3d_y: 0.8814969062805176
  ssim_3d_z: 0.8817794919013977
  duration (sec): 112.8466579914093
  duration (min): 1.8807776331901551
```
